name: Test (lint and typehints)

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint_and_typehints:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff mypy pygame-ce pytmx

    - name: Run ruff
      run: |
        ruff check $(git-ls '*.py')

    - name: Run mypy
      run: |
        mypy main.py